require 'require_all'

require_relative './eh_micro'
require_all 'config/initializers'
require_all 'lib'
require_all 'app/helpers'
require_all 'app/models'
require_all 'app/services'
require_all 'app/consumers/application_consumer.rb'
require_all 'app/consumers'
require_all 'app/controllers/application_controller.rb'
require_all 'app/controllers'
